
/*
The idea is to have a single 'driver' function, which takes an input string or string_view
plus a processing class instance, which carries a few functions, which are each invoked for
each 'element' (word) in the input string.

The 'word' being a file or directory name in the case of pathutils, or a regular text word (or line?)
in the case of unisani, when used on its own.

The point being: both pathutils and unisani publish a set of processor functions, which can be chained
into userland-defined processing functions, which are kept in a simple class instance, and passed to the driver function,
which does the actual iteration over the input string.

The goal is to avoid a lot of (partial) string copying and construction along the way as we 'sanitize' a (larger) input string, such as a path or chunk of input text.
If we do it right, the individual processor functions will use a input string_view and an output string or string_view to deliver the changes, all of which are *small size* so can fit in a static buffer
or even directly into the final output std::string without having to use any local/temporary string allocations along the way, while we feed the input string, bit by bit, through these processor function chains in order to arrive at the desired transliteration/cleanup of the input string.

*/

#include <string>
#include <expected>
#include <memory>
#if 0
#include <exception>
#include <stdexcept>
#else
// objections to exceptions are mostly cf. CppCon/Bloomberg 2024 (IIRC), but his template-exception baseclass "that does it all" is a red herring from my perspective: you *still* get a shitload of exception classes, only now those are generated by the compiler and `using` statements, so it's a non-solution for at least one of his own major complaints.
// Meanwhile, another convention presentation for embedded use of exceptions showed quite scientifically that using exceptions (iff properly adjusted for embedded use contexts, i.e. ditching stdio+iostream cruft) produces both leaner, cleaner and *smaller* code / binary sizes for moderate to large embedded applications.
// I'm more interested in *large* *desktop/server* applications here, and while I loath/don't like the std::expected non-answer for error propagation (you're still doing it and your code is loaded with checks anyhow!), it's better than not having std::expected and std::optional around -- while I don't like to use exceptions for regular error handling.
//
// Anyway, the major valid complaint, AFAIAC, about the std::exception class hierarchy is its non-modifiable and rather restricted error info carrying capacity (a const message string), so we're NOT going to use std::exception for our std::expected-based error propagation here.
// I also agree with the 'out of memory is a system-fatal error' view, so we have *heap allocated* error information object(s), where we pass around pointers to these objects.
//
// Still of two minds about reference-counting vs. single ownership (std::unique_ptr<T>) though, where I'm leaning towards single-ownership...
namespace pathutils {

	// I like the VMS / WindowsNT approach of having error codes as simple integers, divided into zones, carrying both a 'category/library/namespace' id and error id.
	union ErrorCode {
		uint32_t value{0};

		struct alignas(4) Fields {
			enum Severity : unsigned int {
				ECS_SEVERITY_PASS = 0,
				ECS_SEVERITY_ERROR,
				ECS_SEVERITY_CATASTROPHIC
			} severity : 2;						// pass/fail/abort level indicator for fast checks
			unsigned int nameSpace : 10;		// which library / namespace this one's part of 
			unsigned int id : 32 - 10 - 2;		// error id within that library / category / namespace
		} f;
	};

	// ErrorInfo instances are always heap allocated (using `mkErrorInfo()` factory function), and passed around as `std::unique_ptr<ErrorInfo>` pointers inside std::expected<T, ErrorInfoPtr> return values.
	class ErrorInfo {
	public:
		explicit ErrorInfo(const std::string &msg) :
			message(msg)
		{}
		virtual ~ErrorInfo()
		{
		}

		ErrorCode errorCode{0};
		std::string message;

		// userland may inherit from this class and/or extend this class instance's heap space to store additional data to be logged or used in other ways when dealing with this specific error.
	};

	using ErrorInfoPtr = std::unique_ptr<ErrorInfo>;
}
#endif

namespace pathutils {

	// interface definition according to https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern, bacause, well, good grief, this is C++, not C# or Java, now is it?
	template <typename T>
	class SanitationProcessorBase {
	public:
		// -------------- overridable methods -----------------------------------

		std::string process_start(std::string_view &input, size_t& offset) {
			return static_cast<T *>(this)->process_start(input, offset);
		}

		std::string process_element(const std::string_view input, size_t& offset) {
			return static_cast<T *>(this)->process_element(input, offset);
		}

		// Note: because `process_end()` returns an *owning* error info pointer, it must be marked [[nodiscard]] to avoid silent loss of error info!
		//
		// This interface was designed with the intention that the processor instance itself keeps track of any error info which occurs during processing
		// where, at the end of the process, `process_end()` produces that info and passes the responsibility to the caller. This would
		// *implicitly* *clear* the error for the next process run, thus making `process_end()` truly the final call that's involved with
		// the current run: start, process elements, end. Nothing more to do, everything is cleared and ready for another go.
		[[nodiscard]] ErrorInfoPtr process_end(std::string &output, std::string_view &input, size_t offset) {
			return static_cast<T *>(this)->process_end(output, input, offset);
			// return error_;
		}

		// Use this check in your processing loop to see if all is done or an error occurred. Userland implementations should implement the exact check
		// themselves, where part of that SHOULD be a call to `failed()` to see if an actual failure (error) has been registered.
		bool all_done_or_fail(const std::string_view &input, size_t &offset) {
			return static_cast<T *>(this)->all_done_or_fail(input, offset);
		}

		// ---------------------------------------------------------------------

		[[nodiscard]] bool failed(void) const {
			return !!error_;
		}
		void clear_error(void) {
			error_ = nullptr;
		}
		[[nodiscard]] ErrorInfo * peek_error_info(void) const {
			return error_.get();
		}
		void set_error_info(const std::string &msg) {
			error_ = std::make_unique<ErrorInfo>(msg);
		}
		// in case you (userland) have your own ErrorInfo-derived class and wish to use that one:
		void set_error_info(ErrorInfo *err) {
			error_ = err;
		}

	protected:
		ErrorInfoPtr error_{};
	};

	// and one very rudimentary demo implementation of a SanitationProcessorBase-derived class:
	class BasicSanitationProcessorDemo: public SanitationProcessorBase<BasicSanitationProcessorDemo> {
	public:
		std::string process_start(std::string_view &input, size_t& offset) {
			return {};
		}

		std::string process_element(const std::string_view input, size_t& offset) {
			return "x";
		}

		[[nodiscard]] ErrorInfoPtr process_end(std::string &output, std::string_view &input, size_t offset) {
			return std::move(error_);
		}

		bool all_done_or_fail(const std::string_view &input, size_t &offset) {
			return failed() || input.empty();
		}
	};

	// and all that done merely to keep this bit DRY. Sans virtual functions, my my, oh dear, oh dear.
	template <typename T>
	std::expected<std::string, ErrorInfoPtr> sanitize(std::string_view input, SanitationProcessorBase<T> &processor, size_t offset = 0) {
		// process start: initialize output and do any userland preparation your custom SanitationProcessor might need.
		std::string output = processor.process_start(input, offset);
		while (!processor.all_done_or_fail(input, offset)) {
			// process element: the userland-defined process_element() decides what 'an element' is to be,
			// so we just keep calling it until all is done or an error occurs.
			// Meanwhile, process_element() will update the input std::string_view to remove the processed part.
			output += processor.process_element(input, offset);
		}
		// process end: finalize output, report any errors which occurred along the way.
		auto ex = processor.process_end(output, input, offset);
		if (ex != nullptr) {
			return std::unexpected(std::move(ex));
		}
		// extra check: make sure the entire input has been processed
		if (!input.empty()) {
			return std::unexpected(std::make_unique<ErrorInfo>("Sanitization failed: the input wasn't procesed in its entirety"));
		}
		return output;
	}

	// and now for the elemental filter methods (to be used in custom SanitationProcessor implementations):


	// =====================================================================================================


	std::string demo_using_sanitize(std::string_view input) {
		BasicSanitationProcessorDemo processor;

#if 0
		auto [s, ex] = sanitize(input, processor);
		// -->
		// error C3695: 'std::expected<std::string,pathutils::ErrorInfoPtr>': cannot decompose a type containing an anonymous union or struct
		//   see declaration of 'std::expected<std::string,pathutils::ErrorInfoPtr>::<unnamed-tag>'
		// error C2248: 'std::expected<std::string,pathutils::ErrorInfoPtr>::_Value': cannot access private member declared in class 'std::expected<std::string,pathutils::ErrorInfoPtr>'
#else
		auto rv = sanitize(input, processor);
#endif

		// simple code to demonstrate usage of the returned expected<T, E> value:
#if 0
		if (!rv.has_value()) {
			// error occurred
			return "ERROR: " + rv.error()->message;
		}
		return rv.value();
		// -->
		// warning C5272: throwing an object of non-copyable type 'std::bad_expected_access<_Err>' is non-standard. If a copy is needed at runtime it will be made as if by memcpy.
		//   with
		//   [
		//     _Err=pathutils::ErrorInfoPtr
		//   ]
		//   while compiling class template member function 'void std::expected<std::string,pathutils::ErrorInfoPtr>::_Throw_bad_expected_access_lv(void) const'
		// error C2280: 'std::unique_ptr<pathutils::ErrorInfo,std::default_delete<pathutils::ErrorInfo>>::unique_ptr(const std::unique_ptr<pathutils::ErrorInfo,std::default_delete<pathutils::ErrorInfo>> &)': attempting to reference a deleted function
		//   see declaration of 'std::unique_ptr<pathutils::ErrorInfo,std::default_delete<pathutils::ErrorInfo>>::unique_ptr'
		//   'std::unique_ptr<pathutils::ErrorInfo,std::default_delete<pathutils::ErrorInfo>>::unique_ptr(const std::unique_ptr<pathutils::ErrorInfo,std::default_delete<pathutils::ErrorInfo>> &)': function was explicitly deleted
#else
		return rv.value_or(
			// error occurred
			"ERROR: " + rv.error()->message
		);
#endif
	}

}

#include <iostream>

int main(void)
{
	std::cout << pathutils::demo_using_sanitize("This is a demo input string to be sanitized.") << std::endl;
}
